version: '3.8'

services:
  backend:
    build:
      context: ./ikiguide-backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=production
    volumes:
      - ./ikiguide-backend:/app
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build:
      context: ./ikiguide-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./ikiguide-frontend:/app